Repository oVirt/ovirt-engine, pull requests merged in 2024-12, with the labels that each got.

#977 core: only try to unlock vm if vm present
  backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/AddDiskCommand.java
Labels: bug

#925 Issue: Intermittent UI exception while opening the Import Virtual Machine(s) pop-up
  frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/section/main/view/popup/storage/RegisterEntityInfoPanel.java
Labels: Needs Review

#986 core: ability to sort on more space parameters for storage domains
  frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/section/main/view/MainStorageView.java
Labels: enhancement, Needs Review
